name: CI
on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: [main]

jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with: { node-version: 'latest', cache: 'pnpm' }
      - uses: extractions/setup-just@v3
      - run: just prepare
      - run: just lint
      - run: just build
      - run: just test
